title = "Ergohaven's journey"
baseURL = 'https://journey.ergohaven.xyz'

# This is what goes in <html lang="">
languageCode = 'en-us'

# This defines how dates are formatted
defaultContentLanguage = "ru-ru"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes' 
# theme = "hugo-blog-awesome"

# modern way: pull in theme component as hugo module
#[module]
  # Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
  # workspace = "hugo-blog-awesome.work"
  #[module.hugoVersion]
    #extended = true
    #min = "0.87.0"
  #[[module.imports]]
    #path = "github.com/hugo-sid/hugo-blog-awesome"
    #disable = false
[module]
 [[module.imports]]
   path = "github.com/hugo-sid/hugo-blog-awesome"
  [[module.mounts]]
  source = "static"
  target = "assets"

[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
  [services.disqus]
    shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en"
  contentDir = "content/en"
  weight = 2

  [Languages.en-gb.menu]
  # [[Languages.en-gb.menu.main]]
  #   # The page reference (pageRef) is useful for menu highlighting
  #   # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  #   pageRef="/"
  #   name = 'Home'
  #   url = '/'
  #   weight = 10

  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Blog'
    url = '/posts/'
    weight = 20

  [[Languages.en-gb.menu.main]]
    pageRef="docs"
    name = 'Documentation'
    url = '/en-gb/pages/docs'
    weight = 30

  [[Languages.en-gb.menu.main]]
    pageRef="roadmap"
    name = 'Roadmap'
    url = '/pages/roadmap'
    weight = 35

  [[Languages.en-gb.menu.main]]
    pageRef="faq"
    name = 'FAQ'
    url = '/pages/faq'
    weight = 40

  [[Languages.en-gb.menu.main]]
    pageRef="firmware"
    name = 'Firmware & Layouts'
    url = '/pages/firmware'
    weight = 50

  [[Languages.en-gb.menu.main]]
    pageRef="shop"
    name = 'Shop'
    url = 'https://ergohaven.xyz/shop'
    weight = 60

[Languages.en-gb.params]
  sitename = "Ergohaven's journey"
  defaultColor = "auto" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "A platform with useful information, made for you üòâ"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-gb.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Ergohaven's journey"
  description = "A platform with useful information, made for you üòâ"

# Allow to override webmanifest options
[Languages.en-gb.params.webmanifest]
  name = "ergohaven's journey" # will use "params.sitename" or "title" by default
  short_name = "journey" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"


############################## Russian language ################################
[Languages.ru-ru]
  languageName = "Russian"
  languageCode = "ru"
  contentDir = "content/ru"
  weight = 1

  [Languages.ru-ru.menu]
  # [[Languages.ru-ru.menu.main]]
  #   # The page reference (pageRef) is useful for menu highlighting
  #   # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  #   pageRef="/"
  #   name = '–ì–ª–∞–≤–Ω–∞—è'
  #   url = '/'
  #   weight = 10
  
  [[Languages.ru-ru.menu.main]]
    pageRef="posts"
    name = '–ë–ª–æ–≥'
    url = '/posts/'
    weight = 20

  [[Languages.ru-ru.menu.main]]
    pageRef="docs"
    name = '–î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è'
    url = '/pages/docs'
    weight = 30
     
  [[Languages.ru-ru.menu.main]]
    pageRef="roadmap"
    name = 'Roadmap'
    url = '/pages/roadmap'
    weight = 35
     
  [[Languages.ru-ru.menu.main]]
    pageRef="faq"
    name = 'FAQ'
    url = '/pages/faq'
    weight = 40

  [[Languages.ru-ru.menu.main]]
    pageRef="firmware"
    name = '–ü—Ä–æ—à–∏–≤–∫–∞ –∏ —Ä–∞—Å–∫–ª–∞–¥–∫–∏'
    url = '/pages/firmware'
    weight = 50

  [[Languages.ru-ru.menu.main]]
    pageRef="shop"
    name = '–ú–∞–≥–∞–∑–∏–Ω'
    url = 'https://ru.ergohaven.xyz/shop'
    weight = 60

[Languages.ru-ru.params]
  sitename = "Ergohaven's journey"
  defaultColor = "auto" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "–ù–∞—à –±–ª–æ–≥, –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è –∏ –æ—Ç–≤–µ—Ç—ã –Ω–∞ —á–∞—Å—Ç–æ –∑–∞–¥–∞–≤–∞–µ–º—ã–µ –≤–æ–ø—Ä–æ—Å—ã"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.ru-ru.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Ergohaven's journey"
  description = "–ü–ª–∞—Ç—Ñ–æ—Ä–º–∞ —Å –ø–æ–ª–µ–∑–Ω–æ–π –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–µ–π, —Å–ø–µ—Ü–∏–∞–ª—å–Ω–æ –¥–ª—è —Ç–µ–±—è üòâ"

# Allow to override webmanifest options
[Languages.ru-ru.params.webmanifest]
  name = "ergohaven's journey" # will use "params.sitename" or "title" by default
  short_name = "journey" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"


###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/ergohavenxyz"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ergohaven"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@ergohaven"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/ergohaven"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

